version: '3.1'

services:
  php-apache:
    build: Dockerfiles/
    container_name: AppPracticas

    ports:
      - ${PHP_PORT}:80

    volumes:
      - ./src:/var/www/html

    env_file:
      - .env
